export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const FETCHING_USER_DATA = 'FETCHING_USER_DATA';
export const FETCHING_USER_DATA_SUCCESS = 'FETCHING_USER_DATA_SUCCESS';
export const FETCHING_USER_DATA_FAILURE = 'FETCHING_USER_DATA_FAILURE';
